mutation createDirect($userId: Int!, $text: String) {
  createDirect(userId: $userId, text: $text) {
    id
    user {
      ...userFragment
    }
    lastMessage {
      ...messageFragment
    }
    unread
  }
}

mutation deleteDirect($id: Int!) {
  deleteDirect(id: $id)
}

query directs {
  directs {
    id
    user {
      ...userFragment
    }
    lastMessage {
      ...messageFragment
    }
    unread
  }
}

query direct($id: Int!) {
  direct(id: $id) {
    id
    user {
      ...userFragment
    }
    lastMessage {
      ...messageFragment
    }
    unread
  }
}

query currentDirect($userId: Int!) {
  currentDirect(userId: $userId) {
    direct {
      id
      user {
        ...userFragment
      }
      lastMessage {
        ...messageFragment
      }
      unread
    }
    recipient {
      ...userFragment
    }
  }
}

subscription directDeleted {
  direct: directDeleted {
    id
  }
}

subscription directCreated {
  direct: directCreated {
    id
    user {
      ...userFragment
    }
    lastMessage {
      ...messageFragment
    }
    unread
  }
}
