mutation createMessage($chatId: Int, $text: String!) {
  createMessage(chatId: $chatId, text: $text)
}

mutation deleteMessage($id: Int!) {
  deleteMessage(id: $id)
}

mutation readMessage($id: Int!) {
  readMessage(id: $id)
}

mutation typeMessage($chatId: Int!, $username: String) {
  typeMessage(chatId: $chatId, username: $username)
}

query getMessages($chatId: Int!, $offset: Int) {
  messages(chatId: $chatId, offset: $offset) {
    ...messageFragment
  }
}

subscription messageCreated($chatIds: [Int]) {
  messageCreated(chatIds: $chatIds) {
    ...messageFragment
  }
}

subscription messageDeleted($chatIds: [Int]) {
  messageDeleted(chatIds: $chatIds) {
    ids
    chat {
      id
      lastMessage {
        ...messageFragment
      }
      user {
        ...userFragment
      }
      unread
    }
  }
}
