mutation typeMessage($chatId: Int!, $username: String) {
  typeMessage(chatId: $chatId, username: $username)
}

query users($username: String) {
  users(username: $username) {
    ...userFragment
  }
}

query currentUser {
  currentUser {
    ...userFragment
  }
}

subscription onlineUser {
  onlineUser {
    id
    online
    lastSeen
  }
}

subscription typingUser($chatId: Int!) {
  typingUser(chatId: $chatId)
}
